// Generated by ego.
// DO NOT EDIT

//line views/components/homeNavbar.ego:1
package components

import "fmt"
import "html"
import "io"
import "context"

import "github.com/gmohlamo/matcha/models"
import "strings"

func HomeNavbar(w io.Writer, u *models.User) {

//line views/components/homeNavbar.ego:9
	_, _ = io.WriteString(w, "\n<nav class=\"navbar is-dark\" role=\"navigation\" aria-label=\"main navigation\" style=\"width: 100%;\">\n  <div class=\"navbar-brand\">\n    <a role=\"button\" class=\"navbar-burger burger\" aria-label=\"menu\" aria-expanded=\"false\" data-target=\"matchaNavbar\">\n      <span aria-hidden=\"true\"></span>\n      <span aria-hidden=\"true\"></span>\n      <span aria-hidden=\"true\"></span>\n    </a>\n  </div>\n  <div id=\"home-navbar\" class=\"navbar-menu is-primary\">\n    <div class=\"navbar-start\">\n      ")
//line views/components/homeNavbar.ego:19
	if strings.Compare("guest", u.Username) != 0 {
//line views/components/homeNavbar.ego:20
		_, _ = io.WriteString(w, "\n      <a class=\"navbar-item\">\n        Home\n      </a>\n      <a class=\"navbar-item\">\n        Profile\n      </a>\n      <a class=\"navbar-item\">\n        Matches\n      </a>\n      ")
//line views/components/homeNavbar.ego:29
	}
//line views/components/homeNavbar.ego:30
	_, _ = io.WriteString(w, "\n      <a class=\"navbar-item\">\n        Users\n      </a>\n    </div>\n    <div class=\"navbar-end\">\n      <div class=\"navbar-item\">\n        <div class=\"buttons\">\n          <a class=\"button is-primary\">\n            <strong>Logout</strong>\n          </a>\n          <a class=\"button is-primary\">\n            Search users\n          </a>\n        </div>\n      </div>\n    </div>\n  </div>\n</nav>\n")
//line views/components/homeNavbar.ego:48
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
