// Generated by ego.
// DO NOT EDIT

//line views/components/loginModal.ego:1
package components

import "fmt"
import "html"
import "io"
import

//line views/components/loginModal.ego:6
"context"

func LoginModal(w io.Writer) {

	_, _ = io.WriteString(w, "\n<div class=\"container\">\n    <div class=\"modal\" id=\"login_modal\">\n        <div class=\"modal-card animated jackInTheBox\" style=\"width: minmax(250px, 800px); padding: 5%;\">\n            <header class=\"modal-card-head\">\n            <p class=\"modal-card-title\">Lovr Login</p>\n            <button class=\"delete\" aria-label=\"close\"></button>\n            </header>\n            <section class=\"modal-card-body has-icons-left has-icons-right\">\n            <!-- put content here -->\n            <div class=\"field\">\n                <label class=\"label\">Username</label>\n                <div class=\"control has-icons-left has-icons-right\">\n                <input class=\"input\" type=\"text\" placeholder=\"Enter username\" id=\"login_username\" value=\"\">\n                <span class=\"icon is-small is-left\">\n                    <i class=\"fas fa-user\"></i>\n                </span>\n                </div>\n            </div>\n\n            <div class=\"field\">\n                <label class=\"label\">Password</label>\n                <div class=\"control has-icons-left has-icons-right\">\n                <input class=\"input\" id=\"login_password\" type=\"password\" placeholder=\"Password\" value=\"\">\n                <span class=\"icon is-small is-left\">\n                    <i class=\"fas fa-lock\"></i>\n                </span>\n                </div>\n            </div>\n            </section>\n            <footer class=\"modal-card-foot\">\n            <p class=\"control\">\n                <button class=\"button is-primary is-medium is-fullwidth\" id=\"login_button\">\n                Login\n                </button>\n                <button class=\"button is-warning is-medium is-fullwidth\" id=\"forgotPassword\">\n                Forgot Password?\n                </button>\n            </p>\n            </footer>\n        </div>\n    </div>\n</div>\n")
//line views/components/loginModal.ego:48
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
